# Do not edit this file manually! This file is managed by Substratum.

server-name={{ $serverName }}

gamemode={{ $gamemode }}

force-gamemode={{ $forceGamemode ? 'true' : 'false' }}

difficulty={{ $difficulty }}

allow-cheats={{ $allowCheats }}

max-players={{ $maxPlayers }}

online-mode={{ $onlineMode ? 'true' : 'false' }}

allow-list={{ $allowList ? 'true' : 'false' }}

allow-cheats={{ $allowCheats ? 'true' : 'false' }}

server-port={{ $serverPort }}

server-portv6={{ $serverPortV6 }}

view-distance={{ $viewDistance }}

tick-distance={{ $tickDistance }}

player-idle-timeout={{ $playerIdleTimeout }}

max-threads={{ $maxThreads }}

level-name={{ $levelName }}

level-seed={{ $levelSeed }}

default-player-permission-level={{ $defaultPlayerPermissionLevel }}

texturepack-required={{ $texturepackRequired ? 'true' : 'false' }}

content-log-file-enabled={{ $contentLogFileEnabled }}

compression-threshold={{ $compressionThreshold }}

server-authoritative-movement={{ $serverAuthoritativeMovement ? 'true' : 'false' }}

player-movement-score-threshold={{ $playerMovementScoreThreshold }}

player-movement-action-direction-threshold={{ $playerMovementActionDirectionThreshold }}

player-movement-distance-threshold={{ $playerMovementDistanceThreshold }}

player-movement-duration-threshold-in-ms={{ $playerMovementDurationThresholdInMs }}

correct-player-movement={{ $correctPlayerMovement ? 'true' : 'false' }}
